services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dramatiq_pg/schema.sql:/docker-entrypoint-initdb.d/000-queue.sql
      - ./dramatiq_pg/coordination.sql:/docker-entrypoint-initdb.d/000-z-coordination.sql
      - ./tests/func/schema.sql:/docker-entrypoint-initdb.d/001-tests.sql
